BasicTest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testapp/',include('testapp.urls')),
    path('',RedirectView.as_view(url='/testapp/')),
]

testapp/urls.py
from django.urls import path
from . import views

app_name = 'testapp'

urlpatterns = [
    path('',views.IndexView.as_view() , name='index'),
    path('<int:pk>/',views.DetailView.as_view() , name='detail'),
    path('create/',views.CreateView.as_view() , name='create'),
    path('<int:pk>/update/',views.UpdateView.as_view() , name='update'),
    path('<int:pk>/delete/',views.DeleteView.as_view() , name='delete'),
]

testapp/models.py
from django.db import models
from django.urls import reverse

class Result(models.Model):
    name = models.CharField(max_length=50,verbose_name='氏名')
    language = models.PositiveIntegerField(verbose_name='国語')
    math = models.PositiveIntegerField(verbose_name='数学')
    english = models.PositiveIntegerField(verbose_name='英語')


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('testapp:detail',kwargs={'pk':self.pk})

testapp/views.py
from django.views import generic
from .models import Result
from django.urls import reverse_lazy


class IndexView(generic.ListView):
    model = Result

class DetailView(generic.DetailView):
    model = Result
    
class CreateView(generic.edit.CreateView):
    model = Result
    fields = '__all__'

class UpdateView(generic.edit.UpdateView):
    model = Result
    fields = '__all__'

class DeleteView(generic.edit.DeleteView):
    model = Result
    success_url = reverse_lazy('testapp:index')

testapp/templates/testapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#!">成績発表</a>
      </nav>      
    {% block content %}
    {% endblock %}
</body>
</html>

testapp/templates/testapp/result_confirm_delete.html
{% extends './base.html'%}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h2>「{{ result.name }}さん」のテスト結果を削除しますか。</h2>
    <button class="dekete submit" type="submit">削除</button>
</form>
{% endblock %}

testapp/templates/testapp/result_detail.html
{% extends './base.html'%}

{% block content %}

<h2>結果詳細</h2>
<table class="table">
    <thead class="thead-light">
      <tr>
        <th>ID番号</th>
        <th>名前</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{ result.id }}</th>
        <td>{{ result.name }}</td>
      </tr>
    </tbody>
  </table>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>国語(点)</th>
        <th>数学(点)</th>
        <th>英語(点)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{ result.language }}</th>
        <td>{{ result.math }}</td>
        <td>{{ result.english }}</td>
      </tr>
    </tbody>
  </table>
  <div class="text-center">
    <button type="button" class="btn btn-outline-secondary"><a href="{% url 'testapp:index' %}">一覧</a></button>
    <button type="button" class="btn btn-outline-secondary"><a href="{% url 'testapp:create' %}">編集</a></button>
    <button type="button" class="btn btn-outline-secondary"><a href="{% url 'testapp:delete' result.pk %}">削除</a></button>
  </div>
    
{% endblock %}

testapp/templates/testapp/result_form.html
{% extends './base.html'%}

{% block content %}
    <h2>{{ object|yesno:'編集,新規作成' }}</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button>{{ object|yesno:'編集,新規作成'}}</button>
    </form>
    <button type="button" class="btn btn-outline-secondary"><a href="{% url 'testapp:index' %}">一覧</a></button>
{% endblock %}

testapp/templates/testapp/result_list.html
{% extends './base.html'%}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th>ID番号</th>
            <th>名前</th>
            <th>国語(点)</th>
            <th>数学(点)</th>
            <th>英語(点)</th>
            <th>詳細</th>
            
        </tr>
        </thead>
        <tbody>
        {% for result in object_list %}
        <tr>
            <th scope="row">{{ result.id }}</th>
            <td>{{ result.name }}</td>
            <td>{{ result.language }}</td>
            <td>{{ result.math }}</td>
            <td>{{ result.english }}</td>
            <td><button type="button" class="btn btn-outline-secondary"><a href="{% url 'testapp:detail' result.pk %}">詳細</a></button></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="text-center">
        <button><a href="{% url 'testapp:create' %}">新規作成</a></button>
    </div>

{% endblock %}